name: Publish To GitHub Actions

on:
  push:
    branches: [ '*' ]

jobs:
  build-services:
    name: Build Services
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      
      - name: Install dependencies
        working-directory: ./src/Admin/FEWA.Admin.Frontend
        run: npm install
      
      - name: Build
        working-directory: ./src/Admin/FEWA.Admin.Frontend
        run: npm run build

      - name: Copy release
        run: mv ./src/Admin/FEWA.Admin.Frontend/build ./release/
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token	: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: release